# ????????club_db ????????????
spring.datasource.url=jdbc:mysql://localhost:3306/club_db?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
# ??MySQL??????? root?????????
spring.datasource.username=root
# ??MySQL????? 123456??????????????
spring.datasource.password=817010
# ??????????
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ???????
server.port=8888

#??????
spring.security.user.name=zkg
spring.security.user.password=817010

# MyBatis-Plus ??SQL??????????????????SQL?
# MyBatis-Plus???????+???
# 1. ?????????????auditorId ? ???auditor_id?
mybatis-plus.configuration.map-underscore-to-camel-case=true
# 2. ??SQL?????????????
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
# 3. ???????????????????????????
mybatis-plus.global-config.db-config.id-type=auto
mybatis-plus.global-config.db-config.table-underline=true
# ???????update????????????????????????????????
mybatis-plus.global-config.db-config.strategy=update
# 4. ??????????MyBatis-Plus??ClubInfo???
mybatis-plus.type-aliases-package=com.college.club.entity

knife4j.setting.enable-cookie-auth=true
